services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-replica
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    networks:
      - mongodb_network

  mongodb-init:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-init
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    entrypoint: |
      bash -c "
        echo 'Waiting for MongoDB to be ready...'
        sleep 10
        echo 'Initializing single-node replica set...'
        mongosh --host mongodb:27017 --eval '
          try {
            rs.initiate({
              _id: \"rs0\",
              version: 1,
              members: [{ _id: 0, host: \"mongodb:27017\" }]
            });
            console.log(\"Replica set initialized successfully\");
          } catch (e) {
            console.log(\"Replica set already initialized or error:\", e.message);
          }
        '
        echo 'Replica set setup completed'
        echo 'Connect with: mongosh --host localhost:27017'
      "

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
